import Link from 'next/link';
import { Map, ArrowLeft } from 'lucide-react';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white dark:bg-dark-900 text-slate-900 dark:text-white">
      <nav className="border-b border-slate-200 dark:border-white/10 p-6">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <Link href="/" className="text-2xl font-bold font-outfit text-primary-600 flex items-center gap-2">
            <Map size={24} />
            WanderAI
          </Link>
          <Link href="/" className="flex items-center gap-2 text-sm font-medium hover:text-primary-500 transition-colors">
            <ArrowLeft size={16} /> Back Home
          </Link>
        </div>
      </nav>

      <main className="max-w-3xl mx-auto px-6 py-20 prose dark:prose-invert">
        <h1 className="text-4xl md:text-5xl font-bold font-outfit mb-8 not-prose">Terms of Service</h1>
        <p>Last updated: {new Date().toLocaleDateString()}</p>
        
        <h2>1. Acceptance of Terms</h2>
        <p>By accessing and using WanderAI, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our service.</p>

        <h2>2. Description of Service</h2>
        <p>WanderAI provides AI-generated travel itineraries based on user inputs. The itineraries, budgets, and travel agency recommendations are generated by artificial intelligence and are for informational purposes only. We do not guarantee the accuracy, feasibility, or availability of the suggested plans or prices.</p>

        <h2>3. User Responsibilities</h2>
        <p>You are solely responsible for independently verifying all travel requirements, prices, visa regulations, and safety advisories before booking any travel. WanderAI is not a licensed travel agency and is not liable for any issues arising from travel planned using our service.</p>

        <h2>4. Disclaimer of Warranties</h2>
        <p>The Service is provided "as is". We make no warranties regarding the reliability or accuracy of the AI-generated content.</p>
      </main>
    </div>
  );
}
